name        : slang
version     : 2.2.4
release     : 2
source      :
    - ftp://space.mit.edu/pub/davis/slang/v2.2/slang-2.2.4.tar.gz : e334028e0c75c35406d10fe9e1686f36a615dcc6e2af90e8de25d299e8e6129f
homepage    : http://www.jedsoft.org/slang
license     :
    - GPL-2.0
summary     : Programmers library allowing interactive applications
description : |
    S-Lang is a multi-platform programmer's library designed to allow a developer to create robust multi-platform software. It provides facilities required by interactive applications such as display/screen management, keyboard input, keymaps, and so on. The most exciting feature of the library is the slang interpreter that may be easily embedded into a program to make it extensible. It may also be used standalone with the slsh interpreter.
builddeps  :
    - pkgconfig(libpng)
component  : programming
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
check      : |
    make runtests
