name       : slang
version    : 2.3.1a
release    : 5
source     :
    - http://www.jedsoft.org/releases/slang/slang-2.3.1a.tar.bz2 : 54f0c3007fde918039c058965dffdfd6c5aec0bad0f4227192cc486021f08c36
homepage   : http://www.jedsoft.org/slang
license    :
    - GPL-2.0
summary    : Programmers library allowing interactive applications
description: |
    S-Lang is a multi-platform programmer's library designed to allow a developer to create robust multi-platform software. It provides facilities required by interactive applications such as display/screen management, keyboard input, keymaps, and so on. The most exciting feature of the library is the slang interpreter that may be easily embedded into a program to make it extensible. It may also be used standalone with the slsh interpreter.
builddeps  :
    - pkgconfig(libpng)
component  : programming.library
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
check      : |
    # Disable derpy test module for build server 'dumb' terminal
    sed -i "s|TEST_SCRIPTS = test_slsmg.sl|TEST_SCRIPTS =|" modules/Makefile
    LD_PRELOAD='' %make check
