name       : slang
version    : 2.3.2
release    : 6
source     :
    - https://www.jedsoft.org/releases/slang/slang-2.3.2.tar.bz2 : fc9e3b0fc4f67c3c1f6d43c90c16a5c42d117b8e28457c5b46831b8b5d3ae31a
homepage   : https://www.jedsoft.org/slang
license    : GPL-2.0-or-later
component  : programming.library
summary    : Programmers library allowing interactive applications
description: |
    S-Lang is a multi-platform programmer's library designed to allow a developer to create robust multi-platform software. It provides facilities required by interactive applications such as display/screen management, keyboard input, keymaps, and so on. The most exciting feature of the library is the slang interpreter that may be easily embedded into a program to make it extensible. It may also be used standalone with the slsh interpreter.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
check      : |
    # Disable derpy test module for build server 'dumb' terminal
    sed -i "s|TEST_SCRIPTS = test_slsmg.sl|TEST_SCRIPTS =|" modules/Makefile
    LD_PRELOAD='' %make check
